feature/assesment 평가 관련 기능구현: 생성
Kim-s-Crew/SpaghettiCodingClub-BE pull request #147
Opened 2024-05-27 12:12 UTC by kdy9960

관리자가 학생들에 대한 평가를 작성할수 있습니다.

2024-05-27 12:45 UTC, EUNCHAEv1006 requested changes

2024-05-27 12:45 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/assessment/dto/AssessmentResponseDTO.java
> +    public static AssessmentResponseDTO of(Assessment assessment) {
띄어쓰기 부탁드립니다.

2024-05-27 12:45 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/assessment/entity/Assessment.java
>  public class Assessment {
`extends BaseTimeEntity`가 필요할 듯 합니다.

2024-05-27 12:45 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/assessment/service/AssessmentService.java
> +                .createdAt(LocalDateTime.now()) // 현재 시간으로 설정
BaseTimeEntity를 활용하는 것이 더 좋아보입니다.

2024-05-27 12:45 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
모든 엔티티에 `extends BaseTimeEntity` 해주시면 좋을 듯 합니다.

2024-05-27 12:46 UTC, EUNCHAEv1006 commented
고생하셨습니다. 조금만 수정하면 될 것 같습니다.

2024-05-27 14:46 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/assessment/entity/Assessment.java
>  public class Assessment {
네 적용하겠습니다

2024-05-27 14:46 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/assessment/service/AssessmentService.java
> +                .createdAt(LocalDateTime.now()) // 현재 시간으로 설정
BaseTimeEntity가 추가 되어있는지 몰랐네요
바로 추가하겠습니다.

2024-05-27 14:46 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
네 이후에도 계속 추가 하겠습니다.

2024-05-28 00:08 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/assessment/dto/AssessmentResponseDTO.java
> +        return new AssessmentResponseDTO(
return 앞 띄어쓰기 부탁드립니다.!

2024-05-28 00:09 UTC, EUNCHAEv1006 approved these changes

2024-05-28 03:19 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/assessment/dto/AssessmentResponseDTO.java
> +        return new AssessmentResponseDTO(
넵 수정할게요

2024-05-28 03:19 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/assessment/dto/AssessmentResponseDTO.java
> +    public static AssessmentResponseDTO of(Assessment assessment) {
네 알겠습니다

2024-05-28 03:20 UTC, merged