feature/Auth 본인 이메일 인증링크 발송 기능, 추천인 이메일 인증링크 발송 기능, 이메일 검증 3개 기능 구현
Kim-s-Crew/SpaghettiCodingClub-BE pull request #247
Opened 2024-08-09 10:21 UTC by kdy9960

### 설명
이 PR은 '본인 이메일 인증을위한 인증링크발송, 추천인 이메일 인증을 위한 인증링크 발송, 이메일 인증 확인' 총 3개의 기능을 구현한 내용이며 회원가입시 수강생은 본인인증을 통한 가입, 관리자는 본인인증과 추천인인증을 통하여 무분별한 회원가입을 막기위한 내용입니다.

### 주요 변경 사항
수강생의 경우 본인 이메일 인증이 확인된다면 회원가입이 가능하지만 관리자의 경우 본인 이메일을 인증이 확인된 상태여야만 '추천인 이메일 인증링크 발송'기능을 통해서 추천인 관리자의 이메일로 인증링크를 보내 인증후 새로운 관리자로 가입이 가능합니다.
발송 이메일은 토큰 값으로 DB에 저장되며 회원가입이 완료될경우 관련된 토큰값이 삭제되거나, 재발송 요청시 이전 토큰값을 삭제후 발송처리하며, 유효시간이 지난 토큰값은 스케줄러에 의하여 일정시간마다 DB를 정리함으로서 DB성능의 저하를 막을 수 있습니다. 

### 기대 효과
수강생의 경우 본인 인증, 관리자의 경우 본인 인증, 추천인 인증을 통하여 무분별한 사용자의 회원가입을 막을 수 있습니다.

2024-08-13 00:36 UTC, EUNCHAEv1006 requested changes
정말 고생 많으셨습니다.

2024-08-13 00:36 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/repotiroy/EmailVerificationRepository.java
>  package wercsmik.spaghetticodingclub.domain.auth.repotiroy;
repotiroy라는 패키지명에 대한 오타가 있습니다.

2024-08-13 00:36 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/config/EmailConfig.java
> +        mailSender.setUsername(System.getenv("EMAIL_USERNAME"));
추후에 있을 테스트를 위해 `@Value("${}")`를 사용하는 것이 더 좋을 듯 합니다.

2024-08-14 09:34 UTC, EUNCHAEv1006 approved these changes
화이팅!

2024-08-14 09:34 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/repotiroy/EmailVerificationRepository.java
>  package wercsmik.spaghetticodingclub.domain.auth.repotiroy;
바로 수정해놓겠습니다

2024-08-14 09:34 UTC, merged