Feature/auth
Kim-s-Crew/SpaghettiCodingClub-BE pull request #38
Opened 2024-05-09 18:51 UTC by kdy9960

회원가입 기능 구현

2024-05-10 00:59 UTC, EUNCHAEv1006 requested changes

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/SignRequestDTO.java
> +    private String checkPassword;
checkPassword에서도 유효성 검증이 필요할 것 같습니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/SignRequestDTO.java
> +
여긴 띄어쓰기를 제거하는 것이 어떨까요?

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/SignRequestDTO.java
> +    private String adminToken = "";
adminToken이 어떤 것일까요?

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/AuthService.java
> +            throw new CustomException(ErrorCode.EMAIL_ALREADY_EXIST_);
`EMAIL_ALREADY_EXIST` 는 어떨까요? 뒤에 _는 빼는 것이 좋을 것 같아요.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/AuthService.java
> +    public void Signup(SignRequestDTO signRequestDTO) {
Java 네이밍 컨벤션에 따르면 메서드 이름은 소문자로 시작하고, 카멜케이스를 사용해야 하는 걸로 알고 있습니다.
Signup 보단 signup이 적절할 것 같습니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/AuthService.java
> +    public void Signup(SignRequestDTO signRequestDTO) {
signup 메서드는 여러 기능을 수행하고 있어서 메서드를 더 작게 분리하는 건 어떨까요? 이메일 중복 검사, 비밀번호 확인 등등 을 별도의 메소드로 분리하는거죠! 아래는.. 제가 끄적여본 예시 코드입니다.

```
@Service
@RequiredArgsConstructor
public class AuthService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;

    public void signup(SignRequestDTO signRequestDTO) {

        checkDuplicateEmail(signRequestDTO.getEmail());
        validatePassword(signRequestDTO.getPassword(), signRequestDTO.getCheckPassword());
        UserRoleEnum role = determineUserRole(signRequestDTO.getRefereeEmail());
        User user = createUser(signRequestDTO, role);
        userRepository.save(user);
    }

    private void checkDuplicateEmail(String email) {

        if (userRepository.findByEmail(email).isPresent()) {
            throw new CustomException(ErrorCode.EMAIL_ALREADY_EXIST_);
        }
    }

    private void validatePassword(String password, String checkPassword) {

        if (!Objects.equals(password, checkPassword)) {
            throw new CustomException(ErrorCode.PASSWORD_CONFIRMATION_NOT_MATCH);
        }
    }

    private UserRoleEnum determineUserRole(String refereeEmail) {

        return (refereeEmail != null && !refereeEmail.trim().isEmpty()) ? UserRoleEnum.ADMIN : UserRoleEnum.USER;
    }

    private User createUser(SignRequestDTO signRequestDTO, UserRoleEnum role) {

        String encodePassword = passwordEncoder.encode(signRequestDTO.getPassword());

        return new User(signRequestDTO.getUsername(), encodePassword, signRequestDTO.getEmail(), signRequestDTO.getTrack(), signRequestDTO.getRefereeEmail(), role);
    }
}

```

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
> +@Setter
엔티티의 경우 한 번 생성 후에 내부 상태가 변경되지 않도록 관리해야한다고 알고 있습니다.
@Setter는 제거하는 것이 좋을 듯 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
> +@Builder
@Builder를 사용함과 동시에 생성자도 제공하고 있어서 중복된다는 느낌이 있습니다.
빌더 패턴을 사용할 때는 생성자를 private으로 설정하는 건 어떨까요?
그래야 빌더를 통해서만 인스턴스를 생성할 수 있을 듯 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
> +@AllArgsConstructor
위와 같은 이유로 @AllArgsConstructor는 제거하는 것이 좋을 듯 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
> +@NoArgsConstructor
이 어노테이션은 JPA가 엔티티를 재구성할 때 필요한 걸로 알고 있습니다.
따라서 `@NoArgsConstructor(access = AccessLevel.PROTECTED)` 로 설정하는 게 더 올바르지 않을까요?
이렇게 해야 불필요한 객체 생성을 방지할 수 있을 듯 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/UserRoleEnum.java
> +    ADMIN(Authority.ADMIN);  // 관리자 권한
ERD 에서는 Enum('수강생', '관리자', 대기중인 관리자') 이렇게 나누기로 했는데 대기중인 관리자는 어떻게 관리되나요?

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/user/repository/UserRepository.java
> +    Optional<User> findByUsername(String username);
이 코드가 사용되고 있는게 맞나요? 만약 사용하지 않는 코드가 있다면 삭제 부탁드립니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/config/WebSecurityConfig.java
> +//        http.addFilterBefore(new ExceptionHandlerFilter(), JwtAuthenticationFilter.class);
이 부분이 현재 구성에 대한 필요성을 모르겠습니다. 제거를 하거나 필요한 경우 적절한 설명을 주석으로 달아주시면 감사하겠습니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/config/WebSecurityConfig.java
> +//        http.addFilterBefore(jwtAuthenticationFilter(), JwtAuthorizationFilter.class);
이 부분이 현재 구성에 대한 필요성을 모르겠습니다. 제거를 하거나 필요한 경우 적절한 설명을 주석으로 달아주시면 감사하겠습니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/config/WebSecurityConfig.java
> +                        .requestMatchers("/api/auths/**").permitAll() // '/api/user/'로 시작하는 요청 모두 접근 허가
'/api/auths/'로 시작하는 요청 모두 접근 허가를 해야하는 이유가 어떤것일까요?
그리고 주석과 코드의 경로가 일치하지 않습니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/config/WebSecurityConfig.java
> +                        .requestMatchers("/api/user/**").permitAll() // '/api/user/'로 시작하는 요청 모두 접근 허가
'/api/user/'로 시작하는 요청 모두 접근 허가를 해야하는 이유가 어떤것일까요?

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    KAKAOID_ALREADY_EXIST(401, "중복된 카카오ID 입니다."),
소셜 로그인을 사용하지 않는데 이 에러가 필요한 이유가 어떤것일까요?

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    EMAIL_ALREADY_EXIST_(401, "중복된 이메일입니다."),
마지막 _ 는 제거하는 것이 좋을 듯 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    NOT_FOUND_USER(400, "해당 유저가 존재하지 않습니다"),
문장 끝에 점(.)을 추가하는 것이 좋을 듯 합니다.
그리고 `USER_NOT_FOUND` 가 더 자연스러운 것 같습니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    AUTHENTICATION_NOT_HAVE(401, "권한이 없습니다."),
`NO_AUTHORIZATION` 이나 `AUTHORIZATION_NOT_GRANTED` 가 더 자연스러운 표현일 듯 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    EXPIRED_JWT_TOKEN(401, "만료된 JWT token 입니다."),
에러코드의 상태 메세지에서 어떤 곳은 token, Token, 토큰 이렇게 나뉘는데 일관성을 유지해야할 것 같습니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    REVOKED_REFRESH_TOKEN(401, "사용이 중지된 Refresh Token 입니다.");
Refresh Token을 사용하지 않는 걸로 알고 있습니다. 이 에러코드가 필요할까요?

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    REFRESH_TOKEN_NOT_FOUND(404, "Refresh Token을 찾을 수 없습니다."),
Refresh Token을 사용하지 않는 걸로 알고 있습니다. 이 에러코드가 필요할까요?

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    EXPIRED_REFRESH_TOKEN(401, "만료된 Refresh Token 입니다."),
Refresh Token을 사용하지 않는 걸로 알고 있습니다. 이 에러코드가 필요할까요?

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtAuthenticationFilter.java
> +
ObjectMapper 인스턴스는 비용이 많이 드는 객체이기 때문에 매 요청마다 새로 생성하기 보다는 빈(Bean)으로 등록하여 재사용하는 것이 성능적으로 유리할 듯 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtAuthenticationFilter.java
반복적으로 사용되는 문자열(응답 타입, 문자 인코딩 등)은 상수로 선언하여 사용하는 것이 좋을 듯 합니다.
그리고 ObjectMapper를 사용하는 코드가 중복되기 때문에 별도의 메소드로 분리하는 것이 좋아보입니다.
예외 처리도 조금 더 디테일하게 다루는 것이 좋을 듯 합니다.

```
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;

@Slf4j(topic = "로그인 및 JWT 생성")
public class JwtAuthenticationFilter extends UsernamePasswordAuthenticationFilter {

    private static final String CONTENT_TYPE = MediaType.APPLICATION_JSON_VALUE;
    private static final String CHARSET = "UTF-8";

    private final JwtUtil jwtUtil;
    private final ObjectMapper objectMapper;  // 빈으로 주입받음

    @Autowired
    public JwtAuthenticationFilter(JwtUtil jwtUtil, ObjectMapper objectMapper) {
        this.jwtUtil = jwtUtil;
        this.objectMapper = objectMapper;
        setFilterProcessesUrl("/api/auths/login");
    }

    @Override
    protected void successfulAuthentication(HttpServletRequest request,
            HttpServletResponse response, FilterChain chain, Authentication authResult)
            throws IOException {
        log.info("로그인 성공 및 JWT 생성");
        UserDetailsImpl userDetails = (UserDetailsImpl) authResult.getPrincipal();
        String accessToken = jwtUtil.createAccessToken(userDetails.getUsername(), userDetails.getRole());

        writeResponse(response, new CommonResponse<>("로그인 성공", null));
        jwtUtil.addJwtToHeader(accessToken, response);
    }

    @Override
    protected void unsuccessfulAuthentication(HttpServletRequest request,
            HttpServletResponse response, AuthenticationException failed) throws IOException {
        log.info("로그인 실패");
        response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
        writeResponse(response, new CommonResponse<>("로그인 실패", null));
    }

    private void writeResponse(HttpServletResponse response, CommonResponse<?> commonResponse) throws IOException {
        response.setContentType(CONTENT_TYPE);
        response.setCharacterEncoding(CHARSET);
        String jsonResponse = objectMapper.writeValueAsString(commonResponse);
        response.getWriter().write(jsonResponse);
        response.getWriter().flush();
    }
}

```

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtAuthorizationFilter.java
> +            response.setStatus(HttpServletResponse.SC_BAD_REQUEST);
"토큰이 유효하지 않습니다." 이기 때문에 `HttpServletResponse.SC_FORBIDDEN` 이 더 적절하다고 생각합니다.
SC_FORBIDDEN은 클라이언트가 서버에 요청은 인증되었지만, 접근 권한이 없을 때 사용된다고 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtAuthorizationFilter.java
오류 응답을 보내는 로직이 필터의 여러 부분에서 중복될 수 있으므로, 별도의 메서드로 분리하여 코드 중복을 줄여주세요.
그리고 현재 구현에선 토큰이 유효하지 않을 경우의 처리만 있네요.
토큰의 만료, 형식 오류, 서명 오류 등 예외 상황을 구체적으로 만들어주세요.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtUtil.java
> +    private static final Logger logger = LoggerFactory.getLogger("JWT 로그");
@Slf4j 어노테이션을 사용함에도 불구하고 Logger 인스턴스를 생성하고 있어서 중복되는 듯 합니다.
@Slf4j는 이미 log 인스턴스를 제공하기 때문에 logger를 제거하고 log를 사용하는 것이 좋을 듯 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtUtil.java
> +    public void addJwtToHeader(String accessToken,
Bearer 접두사와 함께 토큰을 제공해야 한다고 생각합니다.
BEARED_PREFIX를 포함하는 건 어떨까요?

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsImpl.java
> +        Collection<GrantedAuthority> authorities = new ArrayList<>();
`new ArrayList<>()` 를 사용하는 대신 다른 것을 사용하는 건 어떨까요?
안정성을 위해 불변 리스트가 필요할 것 같습니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsServiceImpl.java
> +                 new UsernameNotFoundException("존재하지 않는 사용자입니다.")
에러 메시지의 사용자의 이메일을 포함하는 건 어떨까요?
이렇게하면 어떤 사용자에 대한 조회가 실패했는지 더 명확히 알 수 있을 듯 합니다.

2024-05-10 00:59 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsServiceImpl.java
사용자가 존재하지 않을 때 발생하는 예외 외에도 로그인 과정에서 발생하는 다른 이벤트에 대한 로깅도 추가하는 것이 어떨까요?

2024-05-10 01:00 UTC, EUNCHAEv1006 commented
![스크린샷 2024-05-10 오전 9 59 51](https://github.com/Kim-s-Crew/SpaghettiCodingClub-BE/assets/129070298/fa240dc8-1d95-4952-a27c-993ce6f77a0b)

이때까지 한 코드리뷰 중에 가장 열심히 오래 했습니다. 
브랜치도 컨벤션에 맞춰주세요!

2024-05-10 05:02 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/AuthService.java
> +            throw new CustomException(ErrorCode.EMAIL_ALREADY_EXIST_);
네 수정할게요

2024-05-10 05:07 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/SignRequestDTO.java
> +    private String checkPassword;
password쪽이랑 동일하게 추가해놓을게요

2024-05-10 05:08 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/SignRequestDTO.java
> +
띄어졌었네요 붙여서 정리해놓겠습니다

2024-05-10 05:10 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/AuthService.java
> +    public void Signup(SignRequestDTO signRequestDTO) {
네 컨벤션에따라서 수정해놓을게요

2024-05-10 05:26 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtUtil.java
> +    public void addJwtToHeader(String accessToken,
그렇군요 찾아보니 JWT를 HTTP 헤더에 추가할 때는 보통 'Bearer ' 접두사를 사용하는 것이 일반적인 관행이라하네요
제안해 주신 대로 `BEARER_PREFIX`를 포함하여 수정하겠습니다.

2024-05-10 05:37 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtUtil.java
> +    private static final Logger logger = LoggerFactory.getLogger("JWT 로그");
@slf4j 기능을 잘 이해를 못했었네요
알려주신대로 logger부분 제거하고 사용하도록 하겠습니다.

2024-05-10 05:39 UTC, kdy9960 commented
세세한 코드리뷰 감사합니다

2024-05-10 07:57 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsImpl.java
> +        Collection<GrantedAuthority> authorities = new ArrayList<>();
제안 대로 안정성을 위해 불변 리스트를 사용해보도록 수정해보겠습니다.
궁금한점이 있는데 불변리스트 적용하면 데이터 내용이 변경이 어려워지는 걸로 알고 있는데 지금 이부분은 권한에 대한 부분인데 나중에 이메일로 인증전에 미승인관리자 권한 부여 형식으로 하는걸로 해서 승인되면 관리자 변환하는걸로 하는걸로 하는데 있어서 적용되는 문제점이 있을까요?

2024-05-10 08:03 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsServiceImpl.java
> +                 new UsernameNotFoundException("존재하지 않는 사용자입니다.")
그렇게하면 어떤 사용자에 대한 조회가 실패했는지 파악은 확실히 잘 되겠네요
다만 궁금해서 의문인게 에러메시지에 사용자 이메일을 나타나게하는거는 보안상 문제는 없나요?
사용자 입장에서는 에러로 이메일이 뜨면 기분이 나쁠수도 있지 않을까 생각이 드네요

2024-05-10 08:13 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsImpl.java
> +        Collection<GrantedAuthority> authorities = new ArrayList<>();
불변 리스트를 사용하는 것은 권한 목록이 생성 시점에 고정되어 이후에 변경되지 않도록 함으로써 시스템의 안정성을 높이는 데 도움이 됩니다. 말씀해주신 것 처럼, 사용자의 권한 상태가 '미승인 관리자'에서 '승인된 관리자'로 변경되는 시나리오에서는 일반적으로 권한 목록을 동적으로 업데이트할 필요가 있습니다. 하지만, `UserDetails`의 권한 목록은 주로 로그인 시에 결정되고 그 이후에는 변경되지 않는 것이 일반적이라고 합니다.

따라서, 사용자의 권한 변경이 필요한 경우(예: 관리자 승인 후), 권한을 업데이트하기 위해 사용자는 로그아웃 후 다시 로그인을 해야 합니다. 이 과정에서 새로운 `UserDetails` 객체가 생성되고, 이 객체는 변경된 권한을 반영하게 됩니다. 

만약 런타임 동안 권한을 변경해야 할 특별한 요구사항이 있는 경우, 권한 변경 로직을 별도로 관리하거나, 권한 변경을 위한 별도의 인터페이스와 서비스를 구현하는 것도 방법이 될 수 있겠네요.!

2024-05-10 08:16 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsServiceImpl.java
> +                 new UsernameNotFoundException("존재하지 않는 사용자입니다.")
오! 말씀 주신 것 처럼 정말 좋은 포인트인 것 같아요.

검색 해보니 `사용자 열거 공격(User Enumeration Attack)`에 취약점을 제공할 수 있다고 하네요.

그럼 내부 로그 활용해서 더 구체적인 정보를 남기는 건 어떻게 생각하세요?

2024-05-13 02:35 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsServiceImpl.java
네 누가 로그인했는지 대해서 와 사용자 일치여부, 비밀번호 일치 여부로 로깅 추가 해볼게요

2024-05-13 02:42 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/SignRequestDTO.java
> +    private String adminToken = "";
처음에 회원가입 코드작성할때 권한에대해서 구분지으려고 넣었던 것인데 추천이메일 여부로 적용하니
필요없어졌네요
지우겠습니다.

2024-05-13 02:42 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsImpl.java
> +        Collection<GrantedAuthority> authorities = new ArrayList<>();
네 알겠습니다.
추후 적용해볼게요

2024-05-13 02:43 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/global/security/UserDetailsServiceImpl.java
> +                 new UsernameNotFoundException("존재하지 않는 사용자입니다.")
네 그렇게 하면 개발자만 확인이 가능하겠네요
추가해 놓겠습니다.

2024-05-14 03:38 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/SignRequestDTO.java
> +    private String checkPassword;
음.. 생각해보니 checkPassword는 유효성 검증이 password와 동일하게 필요할까요?
password와 동일한지 확인하는 것이 필요하지 않을까? 라는 생각도 드네요.

2024-05-16 07:10 UTC, kdy9960 reviewed
세세한 피드백 감사합니다

2024-05-16 07:37 UTC, EUNCHAEv1006 requested changes

2024-05-16 07:37 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/config/WebSecurityConfig.java
> +                        .requestMatchers("/api/user/**").permitAll() // '/api/user/'로 시작하는 요청 모두 접근 허가
음..
로그인을 해야 토큰이 나오고 유저 식별이 가능할텐데
로그인을 하기 전에 비밀번호 재설정을 한다는게 어떤 의미일까요? 계정 찾기 이런걸까요?

2024-05-16 07:37 UTC, EUNCHAEv1006 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    KAKAOID_ALREADY_EXIST(401, "중복된 카카오ID 입니다."),
그렇군요. 그럼 우선 삭제하고, 추후에 추가하는 것이 좋을 듯 합니다.

2024-05-16 09:09 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/SignRequestDTO.java
> +    private String checkPassword;
checkPassword는 애초에 password를 재확인하기 위함이나보니 동일여부 확인 메서드만 존재하면 될거같네요

2024-05-16 10:27 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
> +    KAKAOID_ALREADY_EXIST(401, "중복된 카카오ID 입니다."),
네 삭제해놓을게요

2024-05-16 10:30 UTC, kdy9960 commented on src/main/java/wercsmik/spaghetticodingclub/global/config/WebSecurityConfig.java
> +//        http.addFilterBefore(new ExceptionHandlerFilter(), JwtAuthenticationFilter.class);
필요가 없으니 제거 해놓겠습니다.

2024-05-16 13:17 UTC, EUNCHAEv1006 approved these changes

2024-05-16 13:17 UTC, kdy9960 commented
이야 첫머지다!!!

2024-05-16 13:17 UTC, merged